"""Writes ../ziggurat_tables.h: numpy's ziggurat tables for its normal
sampler, copied exactly, so nprand.c draws the same normals numpy does.

Provenance. The tables are numpy's own constants (numpy/random/src/
distributions/ziggurat_constants.h, BSD-3-Clause). They are read here from
the installed numpy binary rather than retyped, located by their defining
shape: fi is 256 strictly decreasing doubles from 1.0 down to
exp(-r*r/2), wi is the 256 doubles before it, ki the 256 uint64 before that.

Recomputing them instead was tried and does not reproduce numpy's bits:
the textbook construction in 80-digit decimal matches 130 of 256 ki
entries, and in plain doubles 164. numpy's generating script is not
recoverable from its output, so the values are copied, not derived, and
the header says so.

Run once; the output is committed. nprand.c checks the tables against the
checksum printed into the header.
"""

import os
import struct
import zlib

import numpy

R = 3.6541528853610087963519472518

pyd = [f for f in os.listdir(os.path.join(os.path.dirname(numpy.__file__), 'random'))
       if f.startswith('_generator') and f.endswith(('.pyd', '.so'))][0]
blob = open(os.path.join(os.path.dirname(numpy.__file__), 'random', pyd), 'rb').read()

tail = __import__('math').exp(-0.5 * R * R)
off = None
i = blob.find(struct.pack('<d', 1.0))
while i != -1:
    if i + 2048 <= len(blob):
        v = struct.unpack_from('<256d', blob, i)
        if all(v[k] > v[k + 1] for k in range(255)) and abs(v[255] - tail) < 1e-15:
            assert off is None, 'two candidate fi tables'
            off = i
    i = blob.find(struct.pack('<d', 1.0), i + 1)
assert off is not None, 'fi table not found'

raw = blob[off - 4096: off + 2048]
ki = struct.unpack_from('<256Q', raw, 0)
wi = struct.unpack_from('<256d', raw, 2048)
fi = struct.unpack_from('<256d', raw, 4096)
assert ki[1] == 0 and ki[0] == 0x000EF33D8025EF6A, 'ki does not look like ki_double'
crc = zlib.crc32(raw)

out = ['/*',
       ' * ziggurat_tables.h -- numpy\'s ziggurat tables for its standard normal',
       ' * sampler, copied exactly. GENERATED by',
       ' * python-reference/make_ziggurat_tables.py from numpy %s; do not edit.' % numpy.__version__,
       ' *',
       ' * Source: numpy/random/src/distributions/ziggurat_constants.h,',
       ' * Copyright (c) 2005-2025 NumPy Developers, BSD-3-Clause. Copied, not',
       ' * derived: recomputing them does not reproduce numpy\'s bits (see the',
       ' * generating script).',
       ' */',
       '',
       '#ifndef ZIGGURAT_TABLES_H',
       '#define ZIGGURAT_TABLES_H',
       '',
       '#include <stdint.h>',
       '',
       '/* CRC-32 of ki, wi, fi as little-endian bytes, in that order */',
       '#define ZIG_TABLES_CRC32 0x%08XUL' % crc,
       '',
       'static const uint64_t ZIG_KI[256] = {']
for k in range(0, 256, 3):
    out.append('  ' + ', '.join('0x%016XULL' % x for x in ki[k:k + 3]) + ',')
out.append('};\n\nstatic const double ZIG_WI[256] = {')
for k in range(0, 256, 3):
    out.append('  ' + ', '.join(float.hex(x) for x in wi[k:k + 3]) + ',')
out.append('};\n\nstatic const double ZIG_FI[256] = {')
for k in range(0, 256, 3):
    out.append('  ' + ', '.join(float.hex(x) for x in fi[k:k + 3]) + ',')
out.append('};\n\n#endif /* ZIGGURAT_TABLES_H */\n')

here = os.path.dirname(os.path.abspath(__file__))
open(os.path.join(here, '..', 'ziggurat_tables.h'), 'w', newline='\n').write('\n'.join(out))
print('wrote ziggurat_tables.h, crc32 0x%08X' % crc)
